#!/bin/sh -e

if [ ! -h src/github.com/jakubigla/etcdctl ]; then
	mkdir -p src/github.com/jakubigla/
	ln -s ../../.. src/github.com/jakubigla/etcdctl
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}

go install github.com/jakubigla/etcdctl
